name: first
on: push
jobs:
  job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: step_one
        uses: actions/checkout@v2
      - name: step_two
        run: env | sort
  job2:
    name: second_job
    runs-on: windows-latest
    steps:
      - name: step_one
        uses: actions/checkout@v2
      - name: step_two  
        run: "Get-ChildItem Env: | Sort-Object Name"
